name:                blif
version:             0.2.0.1
github:              "foshardware/blif"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/foshardware/blif#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- parsec
- text
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

